// poller.proto — NetMantle distributed poller wire protocol.
//
// This file is the authoritative contract between the NetMantle core
// (server) and remote poller agents (clients).
//
// Protocol design notes
// ---------------------
//
// 1. Transport security: all connections MUST use mTLS. The core presents
//    a server certificate; the poller presents its bootstrap client
//    certificate (provisioned during registration via the REST API).
//    Plain-text connections are rejected at the TLS handshake.
//
// 2. Authentication: the poller sends its bootstrap token in the
//    "authorization" gRPC metadata header as "Bearer <token>". The core
//    verifies the token against the bcrypt hash stored in the `pollers`
//    table (same hash as the REST heartbeat path). Replay protection is
//    provided by a timestamp + nonce in AuthenticateRequest.
//
// 3. Tenant scoping: every RPC carries tenant_id either explicitly or
//    implicitly via the authenticated poller record. The server never
//    returns cross-tenant data regardless of the request.
//
// 4. Job queue semantics: jobs move through states
//    queued → claimed → running → done|failed|cancelled.
//    The ClaimJob RPC is atomic; at-most-one poller wins any given job.
//    Pollers acknowledge completion via ReportResult. A job whose
//    claimed_at is older than the deadline is reclaimed by the scheduler.
//
// 5. Versioning: all messages carry a proto3 schema. The service URL uses
//    "/netmantle.poller.v1/" so future breaking changes get a new version
//    path without breaking deployed v1 pollers.
//
// Code generation
// ---------------
//   # Install toolchain once:
//   go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
//   go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
//
//   # Regenerate from the repository root:
//   protoc --go_out=. --go-grpc_out=. internal/poller/proto/poller.proto
//
// Generated Go files are written according to the go_package option declared
// below (internal/poller/pollerv1). Do not hand-edit generated files.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: internal/poller/proto/poller.proto

package pollerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PollerService_Authenticate_FullMethodName = "/netmantle.poller.v1.PollerService/Authenticate"
	PollerService_ClaimJob_FullMethodName     = "/netmantle.poller.v1.PollerService/ClaimJob"
	PollerService_ReportResult_FullMethodName = "/netmantle.poller.v1.PollerService/ReportResult"
	PollerService_StreamJobs_FullMethodName   = "/netmantle.poller.v1.PollerService/StreamJobs"
	PollerService_Health_FullMethodName       = "/netmantle.poller.v1.PollerService/Health"
)

// PollerServiceClient is the client API for PollerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PollerService is the gRPC service exposed by the NetMantle core for
// remote poller agents to connect to. All RPCs require mTLS and a valid
// bearer token (see AuthenticateRequest).
type PollerServiceClient interface {
	// Authenticate exchanges a bootstrap token for a session lease. The
	// lease is short-lived; pollers must call Authenticate periodically
	// (heartbeat). Returns the poller record and a refresh deadline.
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	// ClaimJob atomically dequeues the next available job for this poller's
	// zone. Returns a single job or NOT_FOUND if the queue is empty.
	ClaimJob(ctx context.Context, in *ClaimJobRequest, opts ...grpc.CallOption) (*ClaimJobResponse, error)
	// ReportResult submits the outcome of a claimed job. The server
	// transitions the job to done or failed and triggers any PostCommit
	// hooks (diff, compliance, search index, notifications).
	ReportResult(ctx context.Context, in *ReportResultRequest, opts ...grpc.CallOption) (*ReportResultResponse, error)
	// StreamJobs is a server-push stream: the core notifies the poller of
	// newly enqueued jobs in real time so pollers do not need to poll.
	// The client sends a single StreamJobsRequest and receives zero or more
	// JobAvailable messages until the stream is cancelled.
	StreamJobs(ctx context.Context, in *StreamJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobAvailable], error)
	// Health returns the poller's current health state and the last-seen
	// timestamp as observed by the core.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type pollerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPollerServiceClient(cc grpc.ClientConnInterface) PollerServiceClient {
	return &pollerServiceClient{cc}
}

func (c *pollerServiceClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, PollerService_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollerServiceClient) ClaimJob(ctx context.Context, in *ClaimJobRequest, opts ...grpc.CallOption) (*ClaimJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimJobResponse)
	err := c.cc.Invoke(ctx, PollerService_ClaimJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollerServiceClient) ReportResult(ctx context.Context, in *ReportResultRequest, opts ...grpc.CallOption) (*ReportResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResultResponse)
	err := c.cc.Invoke(ctx, PollerService_ReportResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollerServiceClient) StreamJobs(ctx context.Context, in *StreamJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobAvailable], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PollerService_ServiceDesc.Streams[0], PollerService_StreamJobs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamJobsRequest, JobAvailable]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PollerService_StreamJobsClient = grpc.ServerStreamingClient[JobAvailable]

func (c *pollerServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PollerService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PollerServiceServer is the server API for PollerService service.
// All implementations must embed UnimplementedPollerServiceServer
// for forward compatibility.
//
// PollerService is the gRPC service exposed by the NetMantle core for
// remote poller agents to connect to. All RPCs require mTLS and a valid
// bearer token (see AuthenticateRequest).
type PollerServiceServer interface {
	// Authenticate exchanges a bootstrap token for a session lease. The
	// lease is short-lived; pollers must call Authenticate periodically
	// (heartbeat). Returns the poller record and a refresh deadline.
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	// ClaimJob atomically dequeues the next available job for this poller's
	// zone. Returns a single job or NOT_FOUND if the queue is empty.
	ClaimJob(context.Context, *ClaimJobRequest) (*ClaimJobResponse, error)
	// ReportResult submits the outcome of a claimed job. The server
	// transitions the job to done or failed and triggers any PostCommit
	// hooks (diff, compliance, search index, notifications).
	ReportResult(context.Context, *ReportResultRequest) (*ReportResultResponse, error)
	// StreamJobs is a server-push stream: the core notifies the poller of
	// newly enqueued jobs in real time so pollers do not need to poll.
	// The client sends a single StreamJobsRequest and receives zero or more
	// JobAvailable messages until the stream is cancelled.
	StreamJobs(*StreamJobsRequest, grpc.ServerStreamingServer[JobAvailable]) error
	// Health returns the poller's current health state and the last-seen
	// timestamp as observed by the core.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedPollerServiceServer()
}

// UnimplementedPollerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPollerServiceServer struct{}

func (UnimplementedPollerServiceServer) Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedPollerServiceServer) ClaimJob(context.Context, *ClaimJobRequest) (*ClaimJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimJob not implemented")
}
func (UnimplementedPollerServiceServer) ReportResult(context.Context, *ReportResultRequest) (*ReportResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportResult not implemented")
}
func (UnimplementedPollerServiceServer) StreamJobs(*StreamJobsRequest, grpc.ServerStreamingServer[JobAvailable]) error {
	return status.Errorf(codes.Unimplemented, "method StreamJobs not implemented")
}
func (UnimplementedPollerServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPollerServiceServer) mustEmbedUnimplementedPollerServiceServer() {}
func (UnimplementedPollerServiceServer) testEmbeddedByValue()                       {}

// UnsafePollerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PollerServiceServer will
// result in compilation errors.
type UnsafePollerServiceServer interface {
	mustEmbedUnimplementedPollerServiceServer()
}

func RegisterPollerServiceServer(s grpc.ServiceRegistrar, srv PollerServiceServer) {
	// If the following call pancis, it indicates UnimplementedPollerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PollerService_ServiceDesc, srv)
}

func _PollerService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollerServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollerService_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollerServiceServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollerService_ClaimJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollerServiceServer).ClaimJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollerService_ClaimJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollerServiceServer).ClaimJob(ctx, req.(*ClaimJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollerService_ReportResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollerServiceServer).ReportResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollerService_ReportResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollerServiceServer).ReportResult(ctx, req.(*ReportResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollerService_StreamJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamJobsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PollerServiceServer).StreamJobs(m, &grpc.GenericServerStream[StreamJobsRequest, JobAvailable]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PollerService_StreamJobsServer = grpc.ServerStreamingServer[JobAvailable]

func _PollerService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollerServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollerService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollerServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PollerService_ServiceDesc is the grpc.ServiceDesc for PollerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PollerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netmantle.poller.v1.PollerService",
	HandlerType: (*PollerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _PollerService_Authenticate_Handler,
		},
		{
			MethodName: "ClaimJob",
			Handler:    _PollerService_ClaimJob_Handler,
		},
		{
			MethodName: "ReportResult",
			Handler:    _PollerService_ReportResult_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _PollerService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamJobs",
			Handler:       _PollerService_StreamJobs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/poller/proto/poller.proto",
}
