// poller.proto — NetMantle distributed poller wire protocol.
//
// This file is the authoritative contract between the NetMantle core
// (server) and remote poller agents (clients).
//
// Protocol design notes
// ---------------------
//
// 1. Transport security: all connections MUST use mTLS. The core presents
//    a server certificate; the poller presents its bootstrap client
//    certificate (provisioned during registration via the REST API).
//    Plain-text connections are rejected at the TLS handshake.
//
// 2. Authentication: the poller sends its bootstrap token in the
//    "authorization" gRPC metadata header as "Bearer <token>". The core
//    verifies the token against the bcrypt hash stored in the `pollers`
//    table (same hash as the REST heartbeat path). Replay protection is
//    provided by a timestamp + nonce in AuthenticateRequest.
//
// 3. Tenant scoping: every RPC carries tenant_id either explicitly or
//    implicitly via the authenticated poller record. The server never
//    returns cross-tenant data regardless of the request.
//
// 4. Job queue semantics: jobs move through states
//    queued → claimed → running → done|failed|cancelled.
//    The ClaimJob RPC is atomic; at-most-one poller wins any given job.
//    Pollers acknowledge completion via ReportResult. A job whose
//    claimed_at is older than the deadline is reclaimed by the scheduler.
//
// 5. Versioning: all messages carry a proto3 schema. The service URL uses
//    "/netmantle.poller.v1/" so future breaking changes get a new version
//    path without breaking deployed v1 pollers.
//
// Code generation
// ---------------
//   # Install toolchain once:
//   go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
//   go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
//
//   # Regenerate from the repository root:
//   protoc --go_out=. --go-grpc_out=. internal/poller/proto/poller.proto
//
// Generated Go files are written according to the go_package option declared
// below (internal/poller/pollerv1). Do not hand-edit generated files.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/poller/proto/poller.proto

package pollerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticateRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PollerName string                 `protobuf:"bytes,1,opt,name=poller_name,json=pollerName,proto3" json:"poller_name,omitempty"` // the name used at REST registration
	TenantId   int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Replay-prevention: the core rejects requests older than 60 seconds.
	ClientTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	Nonce         string                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"` // random hex, min 16 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_internal_poller_proto_poller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_poller_proto_poller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_internal_poller_proto_poller_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetPollerName() string {
	if x != nil {
		return x.PollerName
	}
	return ""
}

func (x *AuthenticateRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *AuthenticateRequest) GetClientTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ClientTime
	}
	return nil
}

func (x *AuthenticateRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type AuthenticateResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Poller *Poller                `protobuf:"bytes,1,opt,name=poller,proto3" json:"poller,omitempty"`
	// The poller should refresh its session before refresh_before expires.
	RefreshBefore *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=refresh_before,json=refreshBefore,proto3" json:"refresh_before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_internal_poller_proto_poller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_poller_proto_poller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_internal_poller_proto_poller_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateResponse) GetPoller() *Poller {
	if x != nil {
		return x.Poller
	}
	return nil
}

func (x *AuthenticateResponse) GetRefreshBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshBefore
	}
	return nil
}

type Poller struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Zone          string                 `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Poller) Reset() {
	*x = Poller{}
	mi := &file_internal_poller_proto_poller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Poller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poller) ProtoMessage() {}

func (x *Poller) ProtoReflect() protoreflect.Message {
	mi := &file_internal_poller_proto_poller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poller.ProtoReflect.Descriptor instead.
func (*Poller) Descriptor() ([]byte, []int) {
	return file_internal_poller_proto_poller_proto_rawDescGZIP(), []int{2}
}

func (x *Poller) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Poller) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Poller) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Poller) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Poller) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type ClaimJobRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PollerId int64                  `protobuf:"varint,1,opt,name=poller_id,json=pollerId,proto3" json:"poller_id,omitempty"`
	TenantId int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Capability filter: the poller only claims jobs of these types.
	SupportedJobTypes []string `protobuf:"bytes,3,rep,name=supported_job_types,json=supportedJobTypes,proto3" json:"supported_job_types,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClaimJobRequest) Reset() {
	*x = ClaimJobRequest{}
	mi := &file_internal_poller_proto_poller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimJobRequest) ProtoMessage() {}

func (x *ClaimJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_poller_proto_poller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimJobRequest.ProtoReflect.Descriptor instead.
func (*ClaimJobRequest) Descriptor() ([]byte, []int) {
	return file_internal_poller_proto_poller_proto_rawDescGZIP(), []int{3}
}

func (x *ClaimJobRequest) GetPollerId() int64 {
	if x != nil {
		return x.PollerId
	}
	return 0
}

func (x *ClaimJobRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ClaimJobRequest) GetSupportedJobTypes() []string {
	if x != nil {
		return x.SupportedJobTypes
	}
	return nil
}

type ClaimJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"` // absent if queue is empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimJobResponse) Reset() {
	*x = ClaimJobResponse{}
	mi := &file_internal_poller_proto_poller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimJobResponse) ProtoMessage() {}

func (x *ClaimJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_poller_proto_poller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimJobResponse.ProtoReflect.Descriptor instead.
func (*ClaimJobResponse) Descriptor() ([]byte, []int) {
	return file_internal_poller_proto_poller_proto_rawDescGZIP(), []int{4}
}

func (x *ClaimJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type Job struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	DeviceId       int64                  `protobuf:"varint,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	JobType        string                 `protobuf:"bytes,5,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`             // "backup" | "probe" | "custom"
	PayloadJson    string                 `protobuf:"bytes,6,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"` // JSON job parameters
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Maximum time the poller may take to report a result before the core
	// reclaims the job and makes it available again.
	Deadline      *durationpb.Duration `protobuf:"bytes,9,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_internal_poller_proto_poller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_internal_poller_proto_poller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_internal_poller_proto_poller_proto_rawDescGZIP(), []int{5}
}

func (x *Job) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Job) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Job) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Job) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *Job) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *Job) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Job) GetDeadline() *durationpb.Duration {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type ReportResultRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	JobId      int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	PollerId   int64                  `protobuf:"varint,2,opt,name=poller_id,json=pollerId,proto3" json:"poller_id,omitempty"`
	TenantId   int64                  `protobuf:"varint,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Success    bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ResultJson string                 `protobuf:"bytes,5,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"` // JSON result payload (job-type specific)
	Error      string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                             // populated when success=false
	// For backup jobs: the artifact bytes.
	Artifacts     []*Artifact `protobuf:"bytes,7,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_internal_poller_proto_poller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_poller_proto_poller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_internal_poller_proto_poller_proto_rawDescGZIP(), []int{6}
}

func (x *ReportResultRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *ReportResultRequest) GetPollerId() int64 {
	if x != nil {
		return x.PollerId
	}
	return 0
}

func (x *ReportResultRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ReportResultRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportResultRequest) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *ReportResultRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReportResultRequest) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_internal_poller_proto_poller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_internal_poller_proto_poller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_internal_poller_proto_poller_proto_rawDescGZIP(), []int{7}
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ReportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_internal_poller_proto_poller_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_poller_proto_poller_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_internal_poller_proto_poller_proto_rawDescGZIP(), []int{8}
}

func (x *ReportResultResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type StreamJobsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PollerId          int64                  `protobuf:"varint,1,opt,name=poller_id,json=pollerId,proto3" json:"poller_id,omitempty"`
	TenantId          int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SupportedJobTypes []string               `protobuf:"bytes,3,rep,name=supported_job_types,json=supportedJobTypes,proto3" json:"supported_job_types,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StreamJobsRequest) Reset() {
	*x = StreamJobsRequest{}
	mi := &file_internal_poller_proto_poller_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamJobsRequest) ProtoMessage() {}

func (x *StreamJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_poller_proto_poller_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamJobsRequest.ProtoReflect.Descriptor instead.
func (*StreamJobsRequest) Descriptor() ([]byte, []int) {
	return file_internal_poller_proto_poller_proto_rawDescGZIP(), []int{9}
}

func (x *StreamJobsRequest) GetPollerId() int64 {
	if x != nil {
		return x.PollerId
	}
	return 0
}

func (x *StreamJobsRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *StreamJobsRequest) GetSupportedJobTypes() []string {
	if x != nil {
		return x.SupportedJobTypes
	}
	return nil
}

// JobAvailable is a hint that a job matching the poller's filters is
// now in the queue. The poller should call ClaimJob immediately.
type JobAvailable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobType       string                 `protobuf:"bytes,1,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	Zone          string                 `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobAvailable) Reset() {
	*x = JobAvailable{}
	mi := &file_internal_poller_proto_poller_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAvailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAvailable) ProtoMessage() {}

func (x *JobAvailable) ProtoReflect() protoreflect.Message {
	mi := &file_internal_poller_proto_poller_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAvailable.ProtoReflect.Descriptor instead.
func (*JobAvailable) Descriptor() ([]byte, []int) {
	return file_internal_poller_proto_poller_proto_rawDescGZIP(), []int{10}
}

func (x *JobAvailable) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *JobAvailable) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollerId      int64                  `protobuf:"varint,1,opt,name=poller_id,json=pollerId,proto3" json:"poller_id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_internal_poller_proto_poller_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_poller_proto_poller_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_poller_proto_poller_proto_rawDescGZIP(), []int{11}
}

func (x *HealthRequest) GetPollerId() int64 {
	if x != nil {
		return x.PollerId
	}
	return 0
}

func (x *HealthRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type HealthResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Healthy              bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	StatusMessage        string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	CoreObservedLastSeen *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=core_observed_last_seen,json=coreObservedLastSeen,proto3" json:"core_observed_last_seen,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_poller_proto_poller_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_poller_proto_poller_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_poller_proto_poller_proto_rawDescGZIP(), []int{12}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *HealthResponse) GetCoreObservedLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.CoreObservedLastSeen
	}
	return nil
}

var File_internal_poller_proto_poller_proto protoreflect.FileDescriptor

const file_internal_poller_proto_poller_proto_rawDesc = "" +
	"\n" +
	"\"internal/poller/proto/poller.proto\x12\x13netmantle.poller.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xa6\x01\n" +
	"\x13AuthenticateRequest\x12\x1f\n" +
	"\vpoller_name\x18\x01 \x01(\tR\n" +
	"pollerName\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12;\n" +
	"\vclient_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"clientTime\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\tR\x05nonce\"\x8e\x01\n" +
	"\x14AuthenticateResponse\x123\n" +
	"\x06poller\x18\x01 \x01(\v2\x1b.netmantle.poller.v1.PollerR\x06poller\x12A\n" +
	"\x0erefresh_before\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rrefreshBefore\"\x96\x01\n" +
	"\x06Poller\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\tR\x04zone\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x127\n" +
	"\tlast_seen\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"{\n" +
	"\x0fClaimJobRequest\x12\x1b\n" +
	"\tpoller_id\x18\x01 \x01(\x03R\bpollerId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12.\n" +
	"\x13supported_job_types\x18\x03 \x03(\tR\x11supportedJobTypes\">\n" +
	"\x10ClaimJobResponse\x12*\n" +
	"\x03job\x18\x01 \x01(\v2\x18.netmantle.poller.v1.JobR\x03job\"\xe3\x02\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\x03R\bdeviceId\x12\x19\n" +
	"\bjob_type\x18\x05 \x01(\tR\ajobType\x12!\n" +
	"\fpayload_json\x18\x06 \x01(\tR\vpayloadJson\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x125\n" +
	"\bdeadline\x18\t \x01(\v2\x19.google.protobuf.DurationR\bdeadline\"\xf4\x01\n" +
	"\x13ReportResultRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x1b\n" +
	"\tpoller_id\x18\x02 \x01(\x03R\bpollerId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\x03R\btenantId\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x1f\n" +
	"\vresult_json\x18\x05 \x01(\tR\n" +
	"resultJson\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12;\n" +
	"\tartifacts\x18\a \x03(\v2\x1d.netmantle.poller.v1.ArtifactR\tartifacts\"8\n" +
	"\bArtifact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"2\n" +
	"\x14ReportResultResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"}\n" +
	"\x11StreamJobsRequest\x12\x1b\n" +
	"\tpoller_id\x18\x01 \x01(\x03R\bpollerId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12.\n" +
	"\x13supported_job_types\x18\x03 \x03(\tR\x11supportedJobTypes\"=\n" +
	"\fJobAvailable\x12\x19\n" +
	"\bjob_type\x18\x01 \x01(\tR\ajobType\x12\x12\n" +
	"\x04zone\x18\x02 \x01(\tR\x04zone\"I\n" +
	"\rHealthRequest\x12\x1b\n" +
	"\tpoller_id\x18\x01 \x01(\x03R\bpollerId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\"\xa4\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x12Q\n" +
	"\x17core_observed_last_seen\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x14coreObservedLastSeen2\xe0\x03\n" +
	"\rPollerService\x12c\n" +
	"\fAuthenticate\x12(.netmantle.poller.v1.AuthenticateRequest\x1a).netmantle.poller.v1.AuthenticateResponse\x12W\n" +
	"\bClaimJob\x12$.netmantle.poller.v1.ClaimJobRequest\x1a%.netmantle.poller.v1.ClaimJobResponse\x12c\n" +
	"\fReportResult\x12(.netmantle.poller.v1.ReportResultRequest\x1a).netmantle.poller.v1.ReportResultResponse\x12Y\n" +
	"\n" +
	"StreamJobs\x12&.netmantle.poller.v1.StreamJobsRequest\x1a!.netmantle.poller.v1.JobAvailable0\x01\x12Q\n" +
	"\x06Health\x12\".netmantle.poller.v1.HealthRequest\x1a#.netmantle.poller.v1.HealthResponseB5Z3github.com/i4Edu/netmantle/internal/poller/pollerv1b\x06proto3"

var (
	file_internal_poller_proto_poller_proto_rawDescOnce sync.Once
	file_internal_poller_proto_poller_proto_rawDescData []byte
)

func file_internal_poller_proto_poller_proto_rawDescGZIP() []byte {
	file_internal_poller_proto_poller_proto_rawDescOnce.Do(func() {
		file_internal_poller_proto_poller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_poller_proto_poller_proto_rawDesc), len(file_internal_poller_proto_poller_proto_rawDesc)))
	})
	return file_internal_poller_proto_poller_proto_rawDescData
}

var file_internal_poller_proto_poller_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_poller_proto_poller_proto_goTypes = []any{
	(*AuthenticateRequest)(nil),   // 0: netmantle.poller.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil),  // 1: netmantle.poller.v1.AuthenticateResponse
	(*Poller)(nil),                // 2: netmantle.poller.v1.Poller
	(*ClaimJobRequest)(nil),       // 3: netmantle.poller.v1.ClaimJobRequest
	(*ClaimJobResponse)(nil),      // 4: netmantle.poller.v1.ClaimJobResponse
	(*Job)(nil),                   // 5: netmantle.poller.v1.Job
	(*ReportResultRequest)(nil),   // 6: netmantle.poller.v1.ReportResultRequest
	(*Artifact)(nil),              // 7: netmantle.poller.v1.Artifact
	(*ReportResultResponse)(nil),  // 8: netmantle.poller.v1.ReportResultResponse
	(*StreamJobsRequest)(nil),     // 9: netmantle.poller.v1.StreamJobsRequest
	(*JobAvailable)(nil),          // 10: netmantle.poller.v1.JobAvailable
	(*HealthRequest)(nil),         // 11: netmantle.poller.v1.HealthRequest
	(*HealthResponse)(nil),        // 12: netmantle.poller.v1.HealthResponse
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 14: google.protobuf.Duration
}
var file_internal_poller_proto_poller_proto_depIdxs = []int32{
	13, // 0: netmantle.poller.v1.AuthenticateRequest.client_time:type_name -> google.protobuf.Timestamp
	2,  // 1: netmantle.poller.v1.AuthenticateResponse.poller:type_name -> netmantle.poller.v1.Poller
	13, // 2: netmantle.poller.v1.AuthenticateResponse.refresh_before:type_name -> google.protobuf.Timestamp
	13, // 3: netmantle.poller.v1.Poller.last_seen:type_name -> google.protobuf.Timestamp
	5,  // 4: netmantle.poller.v1.ClaimJobResponse.job:type_name -> netmantle.poller.v1.Job
	13, // 5: netmantle.poller.v1.Job.created_at:type_name -> google.protobuf.Timestamp
	13, // 6: netmantle.poller.v1.Job.expires_at:type_name -> google.protobuf.Timestamp
	14, // 7: netmantle.poller.v1.Job.deadline:type_name -> google.protobuf.Duration
	7,  // 8: netmantle.poller.v1.ReportResultRequest.artifacts:type_name -> netmantle.poller.v1.Artifact
	13, // 9: netmantle.poller.v1.HealthResponse.core_observed_last_seen:type_name -> google.protobuf.Timestamp
	0,  // 10: netmantle.poller.v1.PollerService.Authenticate:input_type -> netmantle.poller.v1.AuthenticateRequest
	3,  // 11: netmantle.poller.v1.PollerService.ClaimJob:input_type -> netmantle.poller.v1.ClaimJobRequest
	6,  // 12: netmantle.poller.v1.PollerService.ReportResult:input_type -> netmantle.poller.v1.ReportResultRequest
	9,  // 13: netmantle.poller.v1.PollerService.StreamJobs:input_type -> netmantle.poller.v1.StreamJobsRequest
	11, // 14: netmantle.poller.v1.PollerService.Health:input_type -> netmantle.poller.v1.HealthRequest
	1,  // 15: netmantle.poller.v1.PollerService.Authenticate:output_type -> netmantle.poller.v1.AuthenticateResponse
	4,  // 16: netmantle.poller.v1.PollerService.ClaimJob:output_type -> netmantle.poller.v1.ClaimJobResponse
	8,  // 17: netmantle.poller.v1.PollerService.ReportResult:output_type -> netmantle.poller.v1.ReportResultResponse
	10, // 18: netmantle.poller.v1.PollerService.StreamJobs:output_type -> netmantle.poller.v1.JobAvailable
	12, // 19: netmantle.poller.v1.PollerService.Health:output_type -> netmantle.poller.v1.HealthResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_poller_proto_poller_proto_init() }
func file_internal_poller_proto_poller_proto_init() {
	if File_internal_poller_proto_poller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_poller_proto_poller_proto_rawDesc), len(file_internal_poller_proto_poller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_poller_proto_poller_proto_goTypes,
		DependencyIndexes: file_internal_poller_proto_poller_proto_depIdxs,
		MessageInfos:      file_internal_poller_proto_poller_proto_msgTypes,
	}.Build()
	File_internal_poller_proto_poller_proto = out.File
	file_internal_poller_proto_poller_proto_goTypes = nil
	file_internal_poller_proto_poller_proto_depIdxs = nil
}
